[mypy]
python_version = 3.11

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True

[mypy-streamlit.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-langchain_core.*]
ignore_missing_imports = True

[mypy-langchain_ollama.*]
ignore_missing_imports = True

[mypy-langgraph.*]
ignore_missing_imports = True

[mypy-ollama.*]
ignore_missing_imports = True
